name = "Docx"
uuid = "cae6eaf6-1b4f-40a4-a2e0-a9a4c95b4cc3"
authors = ["Tristian Azuara <tristian.azuara@gmail.com>"]
version = "0.1.0"

[deps]
EzXML = "8f5d6c58-4d21-5cfd-889c-e3ad7ee6a615"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
ZipFile = "a5390f91-8eb1-5f08-bee0-b1d1ffed6cea"

[compat]
julia = "1.3"
ZipFile = ">=0.3.9, 1.0.0"
EzXML = ">=1.1.0, 2.0.0"